services:
  redis:
    image: redis/redis-stack:latest
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
    driver: local
