import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;

/**
 * ============================================================================
 * STUDY NOTE: SERIALIZE AND DESERIALIZE BINARY TREE
 * ============================================================================
 *
 * 1. CLARIFYING QUESTIONS
 * ----------------------------------------------------------------------------
 * - "Can the tree contain duplicate values?" 
 *   (Crucial: If all values were strictly unique, we could reconstruct the tree using just its Preorder and Inorder traversals. Duplicates mean we MUST record structural `null` markers).
 * - "The prompt asks for a List of integers. Can I use Java's `null` inside the `List<Integer>` to represent empty child pointers, or must I use a sentinel integer value?" 
 *   (Ensures we agree on the contract. Using `null` is idiomatic in Java Lists, whereas a sentinel like `Integer.MIN_VALUE` requires ensuring the tree values [-1000, 1000] don't conflict).
 * - "Are we optimizing for the compactness of the serialized format, or just structural correctness?" 
 *   (Determines if we need bit-packing or stripping trailing nulls. Usually, standard structural correctness is the priority in interviews).
 * - "Will the deserialization function only receive outputs generated by my serialization function?" 
 *   (Confirms we dictate the protocol and don't have to parse an arbitrary third-party format).
 *
 *
 * 2. THE REASONING JOURNEY
 * ----------------------------------------------------------------------------
 * Core Constraint: 
 * A standard traversal (like Preorder: 1, 2, 3) loses structural information. For example, 
 * a tree skewed left and a tree skewed right might produce the exact same standard traversal 
 * if values repeat. The binding constraint is that we must explicitly encode the "dead ends" 
 * (the null pointers) to unambiguously lock the structure, allowing a single pass to rebuild it.
 *
 * Approach 1: Dual Traversals (The "Unique Values" Trap)
 * What I'd naturally try: I know from computer science class that an Inorder traversal paired 
 * with a Preorder traversal perfectly reconstructs a binary tree. I could just serialize both 
 * arrays and return them concatenated.
 * Why it's flawed: It mathematically fails the moment duplicate values exist in the tree. You 
 * cannot uniquely identify which duplicate acts as the root. It also requires two full passes.
 * - Time Complexity: O(N^2) to rebuild without a HashMap, O(N) with one.
 * - Space Complexity: O(N) — requires storing 2N elements.
 * 
 * Approach 2: BFS Level-Order (The Human-Readable Intermediate)
 * What I'd naturally try: I'll read the tree like a book, top to bottom, left to right, using a 
 * Queue. If I hit a null, I'll literally append a `null` to my list. To rebuild, I'll do the 
 * exact same thing: read the list sequentially, creating nodes, and attaching them to parents 
 * waiting in a Queue.
 * Why it works: It perfectly preserves structure. Every parent guarantees it will process its 
 * next two elements in the list as its left and right children.
 * What work is being repeated: Queue management creates overhead. Rebuilding requires constantly 
 * checking bounds and pulling parents off the queue to attach children.
 * - Time Complexity: O(N) — because every node (and its null children) is queued and dequeued once.
 * - Space Complexity: O(N) — because the Queue holds an entire horizontal level (up to N/2 nodes), 
 *   and the list stores 2N + 1 elements (including nulls).
 *
 * Approach 3: DFS Pre-Order (The Optimal, Elegant Standard)
 * What I'd naturally try: BFS requires a lot of state tracking. A tree is inherently recursive. 
 * What if I just serialize it Top-Down (Preorder: Node -> Left -> Right)? I write the node, 
 * then recurse left, then right. If it's null, I write null. 
 * Why it works: Rebuilding becomes magically simple. Since we wrote Node-Left-Right, if we just 
 * read the list sequentially, the very first item IS the root. The next items BELONG to its left 
 * subtree. Once the left subtree hits its null terminators, the recursion naturally unwinds and 
 * whatever is left in the list automatically belongs to the right subtree.
 * What property removes the bottleneck: The implicit call stack tracks the parent-child relationships 
 * for us. No queues, no index math. We just consume the list linearly via an Iterator.
 * - Time Complexity: O(N) — because we visit every node exactly once during both phases.
 * - Space Complexity: O(N) — bounded by the recursive call stack (O(H)) and the serialized list (O(N)).
 *
 * The Interview Choice:
 * Always write Approach 3 (DFS Pre-Order). It is drastically less code than BFS, mathematically 
 * elegant, and demonstrates a deep mastery of how recursion inherently maps a 1D sequence back 
 * into a 2D tree structure.
 *
 *
 * 3. EDGE CASES
 * ----------------------------------------------------------------------------
 * 1. Empty Tree (root == null) -> Serializes to a list with a single `null`. Deserializes safely to null.
 * 2. Fully Skewed Tree (Linked List) -> Serializes with many consecutive nulls on one side. DFS handles 
 *    this perfectly without StackOverflows up to the 500 node constraint.
 * 3. Duplicate values -> Because we record structure explicitly with nulls, `[1, 1, null, null, 1...]` 
 *    rebuilds flawlessly.
 *
 *
 * 4. DRY RUN (Optimal DFS Pre-Order)
 * ----------------------------------------------------------------------------
 * Original Tree:
 *       1
 *      / \
 *     2   3
 *        / \
 *       4   5
 * 
 * SERIALIZE (Node -> Left -> Right):
 * 1. dfs(1): add 1. Recurse left(2), right(3).
 * 2. dfs(2): add 2. Recurse left(null), right(null).
 *    - dfs(null): add null.
 *    - dfs(null): add null.
 * 3. dfs(3): add 3. Recurse left(4), right(5).
 *    - dfs(4): add 4, add null, add null.
 *    - dfs(5): add 5, add null, add null.
 * Resulting List: [1, 2, null, null, 3, 4, null, null, 5, null, null]
 *
 * DESERIALIZE (Consuming the list via Iterator):
 * - next() = 1. Create Node(1).
 *   - node.left = build():
 *     - next() = 2. Create Node(2).
 *       - node.left = build(): next() = null -> returns null.
 *       - node.right = build(): next() = null -> returns null.
 *       - returns Node(2).
 *   - node.right = build():
 *     - next() = 3. Create Node(3).
 *       - node.left = build(): creates Node(4), consumes two nulls.
 *       - node.right = build(): creates Node(5), consumes two nulls.
 *       - returns Node(3).
 * - returns Node(1).
 * 
 * Pitfalls: 
 * - Using an integer array/index `int i = 0` passed as a method parameter during deserialization. 
 *   In Java, primitives are passed by value, so the left recursion's progress won't be seen by 
 *   the right recursion! You MUST use an `Iterator`, a `Queue`, or a 1-element array `int[] index` 
 *   to maintain the global position.
 *
 * Pattern Recognition: 
 * "When flattening a tree structure into a string/list and rebuilding it -> Use Pre-Order DFS 
 *  and include explicit null markers to act as recursion terminators."
 *
 * Interview Script:
 * "To serialize the tree uniquely, I can't just use standard traversals because they lose structural 
 *  data when duplicates exist. Instead, I'll use a Pre-Order DFS and explicitly append 'null' 
 *  when a child doesn't exist. This acts as a structural terminator. To deserialize, I'll convert 
 *  the list to an Iterator. Because it was serialized Pre-Order, the first element is always the 
 *  root. I construct the node, recursively build its left subtree using the next elements, and 
 *  when it hits the null markers, the recursion naturally unwinds to build the right subtree. 
 *  This takes O(N) time and O(N) space."
 *
 *
 * 5. FOLLOW-UPS
 * ----------------------------------------------------------------------------
 * Q1: How would you serialize a Binary Search Tree (BST) without storing any nulls?
 * A1: For a BST, we can just do a standard Pre-Order traversal without nulls! During deserialization, 
 *     we pass an upper and lower bound (like `min` and `max`). If the next element in the list 
 *     violates the bounds for the left child, we know the left child must be null, and we check 
 *     the right child. This saves massive space by omitting the O(N) null markers.
 *
 * Q2: How would you serialize an N-ary Tree?
 * A2: We can't rely on "left and right". We can either append a special delimiter after the 
 *     children are finished (e.g., Node -> Children -> END_MARKER), or we can store the number 
 *     of children next to the node's value (e.g., `Node(value: 1, childrenCount: 3)`).
 */

public class SerializeDeserializeBinaryTreeStudy {

    // Definition for a binary tree node.
    public static class TreeNode {
        int val;
        TreeNode left;
        TreeNode right;
        TreeNode(int x) { val = x; }
    }

    /**
     * APPROACH 3: DFS PRE-ORDER (The Optimal & Standard Interview Choice)
     * Time: O(N) | Space: O(N)
     */
    public static class CodecDFS {

        // Encodes a tree to a single list.
        public List<Integer> serialize(TreeNode root) {
            List<Integer> serializedList = new ArrayList<>();
            buildSerializedList(root, serializedList);
            return serializedList;
        }

        private void buildSerializedList(TreeNode node, List<Integer> list) {
            // Base case: Terminate the branch explicitly with null
            if (node == null) {
                list.add(null);
                return;
            }

            // Pre-Order: Process Node, then Left, then Right
            list.add(node.val);
            buildSerializedList(node.left, list);
            buildSerializedList(node.right, list);
        }

        // Decodes your encoded list to tree.
        public TreeNode deserialize(List<Integer> data) {
            if (data == null || data.isEmpty()) {
                return null;
            }
            
            // Using an Iterator allows us to sequentially consume the list.
            // It inherently mutates state (moves forward), bypassing Java's pass-by-value primitive limits.
            Iterator<Integer> iterator = data.iterator();
            return buildTree(iterator);
        }

        private TreeNode buildTree(Iterator<Integer> iterator) {
            // Defensive check, though a valid serialized list should perfectly exhaust
            if (!iterator.hasNext()) {
                return null;
            }

            Integer val = iterator.next();
            
            // If we hit our explicit terminator, this branch is dead.
            if (val == null) {
                return null;
            }

            // Because it was serialized Pre-Order, the first non-null we see IS the root of this subproblem.
            TreeNode node = new TreeNode(val);
            
            // The next elements in the iterator strictly belong to the left subtree, until it terminates.
            node.left = buildTree(iterator);
            
            // After the left subtree terminates, the remaining elements belong to the right subtree.
            node.right = buildTree(iterator);

            return node;
        }
    }

    /**
     * APPROACH 2: BFS LEVEL-ORDER (The Iterative Alternative)
     * Time: O(N) | Space: O(N)
     * Included to demonstrate the Queue-based logic, which is highly requested by some companies.
     */
    public static class CodecBFS {

        public List<Integer> serialize(TreeNode root) {
            List<Integer> list = new ArrayList<>();
            if (root == null) return list;

            // Using LinkedList because ArrayDeque throws Exception on add(null)
            Queue<TreeNode> queue = new LinkedList<>();
            queue.offer(root);

            while (!queue.isEmpty()) {
                TreeNode current = queue.poll();
                
                if (current == null) {
                    list.add(null);
                } else {
                    list.add(current.val);
                    // We queue children blindly, even if they are null, to capture structure
                    queue.offer(current.left);
                    queue.offer(current.right);
                }
            }
            
            return list;
        }

        public TreeNode deserialize(List<Integer> data) {
            if (data == null || data.isEmpty() || data.get(0) == null) {
                return null;
            }

            TreeNode root = new TreeNode(data.get(0));
            Queue<TreeNode> queue = new LinkedList<>();
            queue.offer(root);
            
            int i = 1; // Tracks our position in the flat list
            
            while (!queue.isEmpty() && i < data.size()) {
                TreeNode current = queue.poll();

                // Process Left Child
                if (i < data.size() && data.get(i) != null) {
                    current.left = new TreeNode(data.get(i));
                    queue.offer(current.left);
                }
                i++; // Always advance, even if it was null

                // Process Right Child
                if (i < data.size() && data.get(i) != null) {
                    current.right = new TreeNode(data.get(i));
                    queue.offer(current.right);
                }
                i++; // Always advance
            }

            return root;
        }
    }

    /**
     * Helper method to verify trees match by comparing their string outputs.
     */
    private static void verifyTreesMatch(TreeNode original, TreeNode rebuilt) {
        CodecDFS codec = new CodecDFS();
        String origStr = String.valueOf(codec.serialize(original));
        String newStr = String.valueOf(codec.serialize(rebuilt));
        System.out.println("Match? " + origStr.equals(newStr) + " | Structure: " + origStr);
    }

    /**
     * Main method to cross-check approaches against edge cases.
     */
    public static void main(String[] args) {
        CodecDFS codecDFS = new CodecDFS();
        CodecBFS codecBFS = new CodecBFS();

        // Standard Case: The example from the DRY RUN
        //       1
        //      / \
        //     2   3
        //        / \
        //       4   5
        TreeNode standard = new TreeNode(1);
        standard.left = new TreeNode(2);
        TreeNode rightChild = new TreeNode(3);
        rightChild.left = new TreeNode(4);
        rightChild.right = new TreeNode(5);
        standard.right = rightChild;

        System.out.println("--- Standard Tree ---");
        List<Integer> serializedDFS = codecDFS.serialize(standard);
        TreeNode rebuiltDFS = codecDFS.deserialize(serializedDFS);
        verifyTreesMatch(standard, rebuiltDFS);

        List<Integer> serializedBFS = codecBFS.serialize(standard);
        TreeNode rebuiltBFS = codecBFS.deserialize(serializedBFS);
        verifyTreesMatch(standard, rebuiltBFS);


        // Edge Case 1: Empty Tree
        System.out.println("\n--- Empty Tree ---");
        List<Integer> emptySer = codecDFS.serialize(null);
        TreeNode emptyRebuilt = codecDFS.deserialize(emptySer);
        verifyTreesMatch(null, emptyRebuilt);


        // Edge Case 2: Fully Skewed Tree (Linked List essentially)
        // 1 -> 2 -> 3
        TreeNode skewed = new TreeNode(1);
        skewed.left = new TreeNode(2);
        skewed.left.left = new TreeNode(3);
        
        System.out.println("\n--- Skewed Tree ---");
        verifyTreesMatch(skewed, codecDFS.deserialize(codecDFS.serialize(skewed)));


        // Edge Case 3: Duplicates
        //   1
        //  / \
        // 1   1
        TreeNode duplicates = new TreeNode(1);
        duplicates.left = new TreeNode(1);
        duplicates.right = new TreeNode(1);
        
        System.out.println("\n--- Duplicate Values ---");
        verifyTreesMatch(duplicates, codecDFS.deserialize(codecDFS.serialize(duplicates)));
    }
}

/**
 * ============================================================================
 * SUMMARY
 * ============================================================================
 * Core Pattern: Pre-Order DFS with Null Terminators.
 * Key Observation: A tree's shape is lost in standard traversals unless you explicitly 
 *                  record its "dead ends" (null pointers). Doing so allows Pre-Order to 
 *                  perfectly and unambiguously map 2D structure to a 1D list and back.
 * Memorize: `deserialize: val = iterator.next(); if (val == null) return null;`
 *           `node = new Node(val); node.left = build(iter); node.right = build(iter);`
 * Most Common Trap: Passing an primitive `int index = 0` as a parameter to the recursive 
 *                   `deserialize` function. Primitives are passed by value in Java. The 
 *                   right subtree will process the same list indices the left subtree just did. 
 *                   You MUST use a shared state object like an `Iterator` or `int[]`.
 * One-Line Mental Trigger: "Serialize Tree? Pre-order DFS, write nulls, read sequentially with Iterator."
 * ============================================================================
 */

import java.util.*;
import ds_v1.BinaryTree.TreeNode;

/**
 * Serialize and Deserialize Binary Tree
 *
 * ------------------------------------------------------------
 * Core idea
 * ------------------------------------------------------------
 *
 * We need to convert:
 *
 *     Tree -> List<String>
 *
 * and then:
 *
 *     List<String> -> Tree
 *
 * The serialization must preserve:
 *
 * 1. Node values
 * 2. Tree structure
 *
 * Simply storing node values is NOT enough.
 *
 * Example:
 *
 *       1              1
 *      /                \
 *     2                  2
 *
 * Both have preorder:
 *
 *     [1, 2]
 *
 * So we cannot distinguish them.
 *
 * We therefore also store NULL markers.
 *
 * First tree:
 *
 *       1
 *      /
 *     2
 *
 * Preorder with nulls:
 *
 *     [1, 2, null, null, null]
 *
 * Second tree:
 *
 *       1
 *        \
 *         2
 *
 * Preorder with nulls:
 *
 *     [1, null, 2, null, null]
 *
 * Now the structure is uniquely represented.
 *
 * ------------------------------------------------------------
 *
 * Serialization format
 * ------------------------------------------------------------
 *
 * We use:
 *
 *     preorder traversal
 *
 * and write:
 *
 *     node value -> left subtree -> right subtree
 *
 * For a null node, write:
 *
 *     "null"
 *
 * Example:
 *
 *              1
 *            /   \
 *           2     3
 *          / \
 *         4   5
 *
 * Serialization:
 *
 *     [1, 2, 4, null, null, 5, null, null,
 *         3, null, null]
 *
 * ------------------------------------------------------------
 */
public class SerializeDeserialize {

    private static final String NULL_MARKER = "null";

    // ============================================================
    // APPROACH 1: Recursive Preorder Serialization
    // ============================================================
    //
    // Time:  O(N)
    // Space: O(N)
    //
    // Every node and every null pointer is visited once.
    //
    // ------------------------------------------------------------

    public static List<String> serialize(TreeNode<Integer> root) {

        List<String> serializedTree = new ArrayList<>();

        serializePreorder(root, serializedTree);

        return serializedTree;
    }

    /**
     * Serialize the tree using preorder traversal.
     *
     * Order:
     *
     *     current -> left -> right
     *
     * Null children are explicitly stored.
     */
    private static void serializePreorder(
            TreeNode<Integer> currentNode,
            List<String> serializedTree
    ) {

        // A null marker is necessary to preserve structure.
        if (currentNode == null) {
            serializedTree.add(NULL_MARKER);
            return;
        }

        // Store current node first because this is preorder.
        serializedTree.add(String.valueOf(currentNode.data));

        // Serialize left subtree.
        serializePreorder(
                currentNode.left,
                serializedTree
        );

        // Serialize right subtree.
        serializePreorder(
                currentNode.right,
                serializedTree
        );
    }


    // ============================================================
    // DESERIALIZATION
    // ============================================================
    //
    // We read the serialized list in exactly the same order in
    // which we wrote it.
    //
    // This is the key symmetry:
    //
    // serialize:
    //
    //     node
    //     left
    //     right
    //
    // deserialize:
    //
    //     read node
    //     build left
    //     build right
    //
    // ------------------------------------------------------------
    //
    // We need a mutable index.
    //
    // Why?
    //
    // Java passes primitive int by value, so if we simply passed:
    //
    //     int index
    //
    // each recursive call would get its own copy.
    //
    // Using int[] allows all recursive calls to share the same
    // mutable index.
    //
    // ============================================================

    public static TreeNode<Integer> deserialize(
            List<String> serializedTree
    ) {

        // Empty list represents an empty tree.
        if (serializedTree == null || serializedTree.isEmpty()) {
            return null;
        }

        int[] currentIndex = {0};

        return deserializePreorder(
                serializedTree,
                currentIndex
        );
    }

    /**
     * Reconstruct the tree from preorder + null markers.
     */
    private static TreeNode<Integer> deserializePreorder(
            List<String> serializedTree,
            int[] currentIndex
    ) {

        // Read the next serialized value.
        String currentValue =
                serializedTree.get(currentIndex[0]++);

        // A null marker means this child does not exist.
        if (NULL_MARKER.equals(currentValue)) {
            return null;
        }

        // Create the current node.
        TreeNode<Integer> currentNode =
                new TreeNode<>(
                        Integer.parseInt(currentValue)
                );

        // The next values describe the left subtree.
        currentNode.left = deserializePreorder(
                serializedTree,
                currentIndex
        );

        // After the left subtree has been completely consumed,
        // the next values describe the right subtree.
        currentNode.right = deserializePreorder(
                serializedTree,
                currentIndex
        );

        return currentNode;
    }


    // ============================================================
    // APPROACH 2: Iterative Deserialization
    // ============================================================
    //
    // The recursive version is the cleanest.
    //
    // But it is useful to understand how we could reconstruct the
    // tree iteratively.
    //
    // We use a stack of nodes whose children still need to be
    // assigned.
    //
    // Time:  O(N)
    // Space: O(N)
    //
    // ============================================================

    public static TreeNode<Integer> deserializeIterative(
            List<String> serializedTree
    ) {

        if (serializedTree == null
                || serializedTree.isEmpty()
                || NULL_MARKER.equals(serializedTree.get(0))) {
            return null;
        }

        TreeNode<Integer> root =
                new TreeNode<>(
                        Integer.parseInt(serializedTree.get(0))
                );

        /*
         * Each stack entry represents:
         *
         *     "This node still needs children."
         *
         * We process the left child first and then the right child.
         */
        Deque<TreeNode<Integer>> stack =
                new ArrayDeque<>();

        stack.push(root);

        int currentIndex = 1;

        while (currentIndex < serializedTree.size()) {

            TreeNode<Integer> parent = stack.peek();

            /*
             * If the left child has not been assigned yet,
             * assign the next serialized value to the left child.
             */
            if (parent.left == null && parent.right == null) {

                String value =
                        serializedTree.get(currentIndex++);

                if (!NULL_MARKER.equals(value)) {

                    parent.left =
                            new TreeNode<>(
                                    Integer.parseInt(value)
                            );

                    stack.push(parent.left);
                }

            } else {

                /*
                 * Left side has already been processed.
                 * Now process the right child.
                 */
                String value =
                        serializedTree.get(currentIndex++);

                if (!NULL_MARKER.equals(value)) {

                    parent.right =
                            new TreeNode<>(
                                    Integer.parseInt(value)
                            );

                    stack.push(parent.right);
                }

                /*
                 * Both children are now known.
                 *
                 * This node is complete, so remove it from the
                 * stack.
                 */
                if (parent.left != null || parent.right != null) {
                    stack.pop();
                }
            }
        }

        return root;
    }


    // ============================================================
    // Utility: Compare Two Trees
    // ============================================================
    //
    // Useful for verifying:
    //
    //     original tree == deserialized tree
    //
    // We compare both:
    //
    //     values
    //     structure
    //
    // ============================================================

    public static boolean areIdentical(
            TreeNode<Integer> first,
            TreeNode<Integer> second
    ) {

        if (first == null && second == null) {
            return true;
        }

        if (first == null || second == null) {
            return false;
        }

        if (!Objects.equals(first.data, second.data)) {
            return false;
        }

        return areIdentical(first.left, second.left)
                && areIdentical(first.right, second.right);
    }


    // ============================================================
    // Utility: Print Serialized Representation
    // ============================================================

    public static void printSerializedTree(
            List<String> serializedTree
    ) {

        System.out.println(serializedTree);
    }


    // ============================================================
    // Example
    // ============================================================

    public static void main(String[] args) {

        /*
         * Build:
         *
         *              1
         *            /   \
         *           2     3
         *          / \
         *         4   5
         *
         */

        TreeNode<Integer> root =
                new TreeNode<>(1);

        root.left = new TreeNode<>(2);
        root.right = new TreeNode<>(3);

        root.left.left = new TreeNode<>(4);
        root.left.right = new TreeNode<>(5);


        // --------------------------------------------------------
        // Serialize
        // --------------------------------------------------------

        List<String> serializedTree =
                serialize(root);

        System.out.println("Serialized:");
        printSerializedTree(serializedTree);

        /*
         * Expected:
         *
         * [1, 2, 4, null, null, 5, null, null,
         *  3, null, null]
         */


        // --------------------------------------------------------
        // Deserialize
        // --------------------------------------------------------

        TreeNode<Integer> reconstructedTree =
                deserialize(serializedTree);


        // --------------------------------------------------------
        // Verify
        // --------------------------------------------------------

        boolean identical =
                areIdentical(root, reconstructedTree);

        System.out.println(
                "Trees are identical: " + identical
        );

        /*
         * Expected:
         *
         * Trees are identical: true
         */


        // --------------------------------------------------------
        // Empty tree
        // --------------------------------------------------------

        TreeNode<Integer> emptyTree = null;

        List<String> emptySerialization =
                serialize(emptyTree);

        System.out.println(
                "Empty tree serialization: "
                        + emptySerialization
        );

        TreeNode<Integer> reconstructedEmptyTree =
                deserialize(emptySerialization);

        System.out.println(
                "Deserialized empty tree is null: "
                        + (reconstructedEmptyTree == null)
        );
    }
}

import java.util.*;
import ds_v1.BinaryTree.TreeNode;

/**
 * ============================================================================
 *                 SERIALIZE & DESERIALIZE BINARY TREE
 * ============================================================================
 *
 * This file teaches multiple ways to serialize and deserialize a binary tree:
 *
 * 1. DFS / Preorder Recursive
 * 2. BFS / Level Order
 * 3. DFS Iterative
 * 4. Serialize into a single String
 *
 *
 * ============================================================================
 * 1. FIRST UNDERSTAND THE PROBLEM
 * ============================================================================
 *
 * We have a binary tree:
 *
 *
 *                 1
 *                / \
 *               2   3
 *                  /
 *                 4
 *
 *
 * We want to convert this TREE into some data that can be:
 *
 *      Tree  --->  Data
 *
 * This is called:
 *
 *      SERIALIZATION
 *
 *
 * Then we should be able to do:
 *
 *      Data  --->  Same Tree
 *
 * This is called:
 *
 *      DESERIALIZATION
 *
 *
 * ============================================================================
 * 2. WHY DO WE NEED NULL MARKERS?
 * ============================================================================
 *
 * This is the MOST IMPORTANT idea in this problem.
 *
 *
 * Suppose we have:
 *
 *       1
 *      /
 *     2
 *
 *
 * If we only serialize values:
 *
 *      [1, 2]
 *
 *
 * Can we know whether 2 is:
 *
 *      1's LEFT child?
 *
 * or
 *
 *      1's RIGHT child?
 *
 * No!
 *
 *
 * Both of these trees could produce [1, 2]:
 *
 *
 *       1                 1
 *      /                   \
 *     2                     2
 *
 *
 * Therefore:
 *
 *      VALUES ALONE ARE NOT ENOUGH.
 *
 *
 * We must store information about missing children.
 *
 *
 * For example:
 *
 *       1
 *      /
 *     2
 *
 *
 * Preorder traversal:
 *
 *      1
 *      2
 *      null
 *      null
 *      null
 *
 *
 * So:
 *
 *      [1, 2, null, null, null]
 *
 *
 * Now the structure is completely preserved.
 *
 *
 * ============================================================================
 * 3. WHY PREORDER?
 * ============================================================================
 *
 * Preorder traversal is:
 *
 *              ROOT
 *             /    \
 *          LEFT    RIGHT
 *
 *
 * For our tree:
 *
 *
 *                 1
 *                / \
 *               2   3
 *                  /
 *                 4
 *
 *
 * Preorder visits:
 *
 *      1 -> 2 -> null -> null -> 3 -> 4 -> null -> null -> null
 *
 *
 * So:
 *
 *      [1, 2, null, null, 3, 4, null, null, null]
 *
 *
 * Why is this convenient?
 *
 * Because while deserializing:
 *
 *      First value = ROOT
 *
 *      Next values = LEFT subtree
 *
 *      Remaining values = RIGHT subtree
 *
 *
 * This matches the recursive structure of a binary tree perfectly.
 *
 *
 * ============================================================================
 * 4. THE CORE IDEA
 * ============================================================================
 *
 * SERIALIZATION:
 *
 *      Tree
 *       |
 *       v
 *      preorder traversal
 *       |
 *       v
 *      store values + nulls
 *
 *
 * DESERIALIZATION:
 *
 *      values + nulls
 *       |
 *       v
 *      read from left to right
 *       |
 *       v
 *      reconstruct recursively
 *
 *
 * The beautiful part is:
 *
 *      SERIALIZE and DESERIALIZE use the SAME TREE STRUCTURE.
 *
 * ============================================================================
 */
public class SerializeDeserialize {

    /*
     * =========================================================================
     *                           EXAMPLE TREE
     * =========================================================================
     *
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * Nodes:
     *
     *      1
     *     / \
     *    2   3
     *       /
     *      4
     *
     *
     * Preorder:
     *
     *      1
     *      2
     *      null
     *      null
     *      3
     *      4
     *      null
     *      null
     *      null
     *
     *
     * Serialized:
     *
     *      [1, 2, null, null, 3, 4, null, null, null]
     *
     *
     * =========================================================================
     */


    // =========================================================================
    // 1. DFS / PREORDER SERIALIZATION
    // =========================================================================

    /**
     * SERIALIZATION
     * -------------
     *
     * Convert a binary tree into a List<String>.
     *
     *
     * We use PREORDER:
     *
     *      ROOT -> LEFT -> RIGHT
     *
     *
     * Example:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * Traversal:
     *
     *      1
     *      2
     *      null
     *      null
     *      3
     *      4
     *      null
     *      null
     *      null
     *
     *
     * Result:
     *
     *      [1, 2, null, null, 3, 4, null, null, null]
     */
    public static List<String> serialize(TreeNode<Integer> root) {

        /*
         * We need somewhere to store our serialized tree.
         *
         * Example:
         *
         *      result = []
         */
        List<String> result = new ArrayList<>();

        /*
         * Start recursively from root.
         */
        serializeHelper(root, result);

        return result;
    }


    /**
     * Recursive helper for serialization.
     *
     *
     * The recursive pattern is:
     *
     *      if node == null
     *          store null
     *          return
     *
     *      store node
     *      serialize left
     *      serialize right
     *
     *
     * In other words:
     *
     *
     *              node
     *             /    \
     *            /      \
     *        serialize  serialize
     *          left       right
     */
    private static void serializeHelper(
            TreeNode<Integer> node,
            List<String> result) {

        // =====================================================================
        // BASE CASE
        // =====================================================================
        //
        // If there is no node, we MUST store null.
        //
        // Why?
        //
        // Because null tells deserialization:
        //
        //      "There is no node here."
        //
        // Without this information, the tree structure would be lost.
        //
        if (node == null) {
            result.add("null");
            return;
        }


        // =====================================================================
        // STEP 1: STORE ROOT
        // =====================================================================
        //
        // This is PREORDER:
        //
        //      ROOT
        //      LEFT
        //      RIGHT
        //
        result.add(String.valueOf(node.data));


        // =====================================================================
        // STEP 2: SERIALIZE LEFT SUBTREE
        // =====================================================================

        serializeHelper(node.left, result);


        // =====================================================================
        // STEP 3: SERIALIZE RIGHT SUBTREE
        // =====================================================================

        serializeHelper(node.right, result);
    }


    // =========================================================================
    // TRACE: DFS SERIALIZATION
    // =========================================================================

    /*
     *
     * Tree:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * Call:
     *
     *      serializeHelper(1)
     *
     *
     * STEP 1
     * ------
     *
     * node = 1
     *
     * Store 1
     *
     * result:
     *
     *      [1]
     *
     *
     * Go LEFT
     *
     *
     * STEP 2
     * ------
     *
     * node = 2
     *
     * Store 2
     *
     * result:
     *
     *      [1, 2]
     *
     *
     * Go LEFT
     *
     *
     * STEP 3
     * ------
     *
     * node = null
     *
     * Store null
     *
     * result:
     *
     *      [1, 2, null]
     *
     *
     * Go RIGHT
     *
     *
     * STEP 4
     * ------
     *
     * node = null
     *
     * Store null
     *
     * result:
     *
     *      [1, 2, null, null]
     *
     *
     * 2 is now completely processed.
     *
     *
     * Go back to 1.
     *
     *
     * STEP 5
     * ------
     *
     * node = 3
     *
     * Store 3
     *
     * result:
     *
     *      [1, 2, null, null, 3]
     *
     *
     * Go LEFT.
     *
     *
     * STEP 6
     * ------
     *
     * node = 4
     *
     * Store 4
     *
     * result:
     *
     *      [1, 2, null, null, 3, 4]
     *
     *
     * 4 has no children:
     *
     *      null
     *      null
     *
     *
     * result:
     *
     *      [1, 2, null, null, 3, 4, null, null]
     *
     *
     * Finally, 3's RIGHT child is null:
     *
     *      null
     *
     *
     * FINAL:
     *
     *      [1, 2, null, null, 3, 4, null, null, null]
     *
     */


    // =========================================================================
    // 2. DFS / PREORDER DESERIALIZATION
    // =========================================================================

    /**
     * DESERIALIZATION
     * ---------------
     *
     * Convert:
     *
     *      [1, 2, null, null, 3, 4, null, null, null]
     *
     * back into:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * The important problem:
     *
     * We need to keep track of which element we are currently reading.
     *
     *
     * Example:
     *
     *      index = 0
     *
     *      stream:
     *
     *      [1, 2, null, null, 3, 4, null, null, null]
     *       ^
     *       |
     *      index
     *
     *
     * Java does NOT allow us to pass an int by reference.
     *
     * So we use:
     *
     *      int[] index = new int[1];
     *
     *
     * Why does this work?
     *
     * Arrays are objects.
     *
     * The recursive calls all share the SAME array.
     *
     * Therefore:
     *
     *      index[0]++
     *
     * is visible to every recursive call.
     */
    public static TreeNode<Integer> deserialize(List<String> stream) {

        /*
         * index[0] = current position in serialized data.
         *
         * Initially:
         *
         *      [1, 2, null, null, 3, ...]
         *       ^
         *
         *      index[0] = 0
         */
        int[] index = new int[1];

        return deserializeHelper(stream, index);
    }


    /**
     * Recursive deserialization.
     *
     *
     * The KEY INVARIANT is:
     *
     *      index[0] always points to the next value
     *      that we need to consume.
     *
     *
     * For every call:
     *
     *      1. Read current value
     *      2. Move index forward
     *      3. If null -> return null
     *      4. Otherwise create node
     *      5. Build left subtree
     *      6. Build right subtree
     */
    private static TreeNode<Integer> deserializeHelper(
            List<String> stream,
            int[] index) {

        // =====================================================================
        // STEP 1: READ CURRENT VALUE
        // =====================================================================

        String val = stream.get(index[0]);


        // =====================================================================
        // STEP 2: MOVE POINTER
        // =====================================================================
        //
        // VERY IMPORTANT:
        //
        // We consume the current value.
        //
        // Therefore move to the next value.
        //
        index[0]++;


        // =====================================================================
        // STEP 3: NULL?
        // =====================================================================
        //
        // If serialized value is "null":
        //
        //      there is no node here.
        //
        // So return null.
        //
        if (val.equals("null")) {
            return null;
        }


        // =====================================================================
        // STEP 4: CREATE NODE
        // =====================================================================

        TreeNode<Integer> node =
                new TreeNode<>(Integer.parseInt(val));


        // =====================================================================
        // STEP 5: BUILD LEFT SUBTREE
        // =====================================================================
        //
        // The next serialized values belong to the LEFT subtree.
        //
        node.left = deserializeHelper(stream, index);


        // =====================================================================
        // STEP 6: BUILD RIGHT SUBTREE
        // =====================================================================
        //
        // Once the complete left subtree is reconstructed,
        // the next values belong to the RIGHT subtree.
        //
        node.right = deserializeHelper(stream, index);


        return node;
    }


    // =========================================================================
    // TRACE: DFS DESERIALIZATION
    // =========================================================================

    /*
     *
     * Serialized:
     *
     * [1, 2, null, null, 3, 4, null, null, null]
     *
     * index:
     *
     *  0  1     2     3  4  5     6     7     8
     *  |  |     |     |  |  |     |     |     |
     * [1,  2,  null, null, 3, 4,  null,  null, null]
     *
     *
     * -------------------------------------------------------------------------
     * CALL 1
     * -------------------------------------------------------------------------
     *
     * index = 0
     * value = 1
     *
     * Create:
     *
     *       1
     *
     * Now:
     *
     *      node.left = deserialize(...)
     *
     *
     * -------------------------------------------------------------------------
     * CALL 2
     * -------------------------------------------------------------------------
     *
     * index = 1
     * value = 2
     *
     * Create:
     *
     *       2
     *
     * Build 2's LEFT.
     *
     *
     * -------------------------------------------------------------------------
     * CALL 3
     * -------------------------------------------------------------------------
     *
     * index = 2
     * value = null
     *
     * return null
     *
     * Therefore:
     *
     *       2
     *      /
     *   null
     *
     *
     * -------------------------------------------------------------------------
     * CALL 4
     * -------------------------------------------------------------------------
     *
     * index = 3
     * value = null
     *
     * return null
     *
     * Therefore:
     *
     *       2
     *      / \
     *   null null
     *
     *
     * Node 2 is complete.
     *
     *
     * Return to node 1.
     *
     *
     * -------------------------------------------------------------------------
     * CALL 5
     * -------------------------------------------------------------------------
     *
     * index = 4
     * value = 3
     *
     * Create:
     *
     *       3
     *
     *
     * Build LEFT.
     *
     *
     * -------------------------------------------------------------------------
     * CALL 6
     * -------------------------------------------------------------------------
     *
     * index = 5
     * value = 4
     *
     * Create:
     *
     *       4
     *
     * 4's left = null
     * 4's right = null
     *
     *
     * So:
     *
     *       4
     *      / \
     *   null null
     *
     *
     * Return to 3.
     *
     *
     * 3's right = null.
     *
     *
     * Final tree:
     *
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * EXACT ORIGINAL TREE!
     *
     */


    // =========================================================================
    // 3. BFS / LEVEL ORDER SERIALIZATION
    // =========================================================================

    /**
     * BFS = Breadth First Search.
     *
     * Instead of going deep first:
     *
     *      ROOT -> LEFT -> RIGHT
     *
     * We go level by level:
     *
     *
     *                 1        <- level 0
     *                / \
     *               2   3      <- level 1
     *                  /
     *                 4         <- level 2
     *
     *
     * BFS order:
     *
     *      1 -> 2 -> 3 -> 4
     *
     *
     * But again:
     *
     *      NULLS MUST BE STORED.
     *
     *
     * For example:
     *
     *       1
     *      /
     *     2
     *
     *
     * BFS with nulls:
     *
     *      1
     *      2
     *      null
     *      null
     *      null
     *
     *
     * Why?
     *
     * Because we need to know:
     *
     *      2 is LEFT child of 1
     *
     * rather than:
     *
     *      2 is RIGHT child of 1
     */
    public static List<String> serializeBFS(TreeNode<Integer> root) {

        List<String> result = new ArrayList<>();


        // Empty tree.
        //
        // We can simply return an empty list.
        //
        if (root == null) {
            return result;
        }


        /*
         * Queue is perfect for BFS.
         *
         * FIFO:
         *
         *      First In -> First Out
         */
        Queue<TreeNode<Integer>> queue = new LinkedList<>();

        queue.offer(root);


        while (!queue.isEmpty()) {

            /*
             * Remove the next node to process.
             */
            TreeNode<Integer> node = queue.poll();


            // =================================================================
            // NULL NODE
            // =================================================================
            //
            // We MUST record it.
            //
            if (node == null) {
                result.add("null");
                continue;
            }


            // =================================================================
            // NORMAL NODE
            // =================================================================

            result.add(String.valueOf(node.data));


            /*
             * IMPORTANT:
             *
             * Add BOTH children.
             *
             * Even if they are null.
             *
             * Why?
             *
             * Because null carries structural information.
             */
            queue.offer(node.left);
            queue.offer(node.right);
        }


        return result;
    }


    // =========================================================================
    // BFS TRACE
    // =========================================================================

    /*
     *
     * Tree:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * Initial:
     *
     * queue:
     *
     *      [1]
     *
     *
     * Process 1:
     *
     * result:
     *
     *      [1]
     *
     * queue:
     *
     *      [2, 3]
     *
     *
     * Process 2:
     *
     * result:
     *
     *      [1, 2]
     *
     * queue:
     *
     *      [3, null, null]
     *
     *
     * Process 3:
     *
     * result:
     *
     *      [1, 2, 3]
     *
     * queue:
     *
     *      [null, null, 4, null]
     *
     *
     * Process null:
     *
     * result:
     *
     *      [1, 2, 3, null]
     *
     *
     * Process null:
     *
     * result:
     *
     *      [1, 2, 3, null, null]
     *
     *
     * Process 4:
     *
     * result:
     *
     *      [1, 2, 3, null, null, 4]
     *
     *
     * Then 4's children:
     *
     *      null
     *      null
     *
     *
     * Final:
     *
     *      [1, 2, 3, null, null, 4, null, null, null]
     *
     */


    // =========================================================================
    // 4. BFS / LEVEL ORDER DESERIALIZATION
    // =========================================================================

    /**
     * Reconstruct the tree from BFS data.
     *
     *
     * Example:
     *
     *      [1, 2, 3, null, null, 4, null, null, null]
     *
     *
     * We know:
     *
     *      First value = root
     *
     *      1
     *
     *
     * Then:
     *
     *      next value = root.left
     *      next value = root.right
     *
     *
     * So:
     *
     *             1
     *            / \
     *           2   3
     *
     *
     * Then process node 2:
     *
     *      next two values = 2's children
     *
     * Then process node 3:
     *
     *      next two values = 3's children
     *
     *
     * This is why we keep a queue of nodes whose children
     * still need to be assigned.
     */
    public static TreeNode<Integer> deserializeBFS(
            List<String> stream) {

        // Empty serialized data means empty tree.
        if (stream.isEmpty()) {
            return null;
        }


        /*
         * First value MUST be the root.
         *
         * Example:
         *
         *      stream = [1, 2, 3, ...]
         *
         *      root = 1
         */
        TreeNode<Integer> root =
                new TreeNode<>(Integer.parseInt(stream.get(0)));


        /*
         * Queue contains nodes whose children we still need to build.
         *
         * Initially:
         *
         *      queue = [root]
         */
        Queue<TreeNode<Integer>> queue =
                new LinkedList<>();

        queue.offer(root);


        /*
         * i points to the next serialized value.
         *
         * We already consumed index 0 for root.
         *
         * Therefore:
         *
         *      i = 1
         */
        int i = 1;


        while (!queue.isEmpty() && i < stream.size()) {

            /*
             * Get the next parent node.
             *
             * This node needs:
             *
             *      LEFT
             *      RIGHT
             *
             * assigned.
             */
            TreeNode<Integer> current = queue.poll();


            // =================================================================
            // LEFT CHILD
            // =================================================================

            /*
             * Read stream[i].
             */
            if (!stream.get(i).equals("null")) {

                /*
                 * Create left child.
                 */
                current.left =
                        new TreeNode<>(
                                Integer.parseInt(stream.get(i))
                        );


                /*
                 * This new node will eventually need its
                 * own children.
                 *
                 * Therefore add it to queue.
                 */
                queue.offer(current.left);
            }

            // Move to next serialized value.
            i++;


            // =================================================================
            // RIGHT CHILD
            // =================================================================

            /*
             * Make sure there is still something to read.
             */
            if (i < stream.size()
                    && !stream.get(i).equals("null")) {

                /*
                 * Create right child.
                 */
                current.right =
                        new TreeNode<>(
                                Integer.parseInt(stream.get(i))
                        );


                /*
                 * This node will need its children later.
                 */
                queue.offer(current.right);
            }

            // Move to next serialized value.
            i++;
        }


        return root;
    }


    // =========================================================================
    // BFS DESERIALIZATION TRACE
    // =========================================================================

    /*
     *
     * Input:
     *
     *      [1, 2, 3, null, null, 4, null, null, null]
     *
     *
     * First:
     *
     *      root = 1
     *
     * queue:
     *
     *      [1]
     *
     *
     * ---------------------------------------------------------
     * Process node 1
     * ---------------------------------------------------------
     *
     * next = 2
     *
     *      1.left = 2
     *
     * next = 3
     *
     *      1.right = 3
     *
     *
     * Tree:
     *
     *          1
     *         / \
     *        2   3
     *
     *
     * queue:
     *
     *      [2, 3]
     *
     *
     * ---------------------------------------------------------
     * Process node 2
     * ---------------------------------------------------------
     *
     * next = null
     *
     *      2.left = null
     *
     * next = null
     *
     *      2.right = null
     *
     *
     * queue:
     *
     *      [3]
     *
     *
     * ---------------------------------------------------------
     * Process node 3
     * ---------------------------------------------------------
     *
     * next = 4
     *
     *      3.left = 4
     *
     * next = null
     *
     *      3.right = null
     *
     *
     * Final:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     */


    // =========================================================================
    // 5. ITERATIVE DFS SERIALIZATION
    // =========================================================================

    /**
     * We can also perform preorder DFS WITHOUT recursion.
     *
     *
     * Recursive preorder:
     *
     *      process root
     *      process left
     *      process right
     *
     *
     * Recursion internally uses a STACK.
     *
     * So we can create our own stack and simulate recursion.
     *
     *
     * The trick:
     *
     * Stack is LIFO:
     *
     *      Last In -> First Out
     *
     *
     * We want:
     *
     *      LEFT before RIGHT
     *
     *
     * Therefore:
     *
     *      push RIGHT first
     *      push LEFT second
     *
     *
     * Stack:
     *
     *      push(right)
     *      push(left)
     *
     *
     * LEFT is now on top.
     *
     * Therefore LEFT gets processed first.
     */
    public static List<String> serializeDFSIterative(
            TreeNode<Integer> root) {

        List<String> result = new ArrayList<>();


        /*
         * Stack is used instead of recursive call stack.
         */
        Stack<TreeNode<Integer>> stack =
                new Stack<>();


        /*
         * IMPORTANT:
         *
         * Even if root == null, push it.
         *
         * Why?
         *
         * Because an empty tree should serialize to:
         *
         *      [null]
         *
         * This preserves the fact that the tree itself is empty.
         */
        stack.push(root);


        while (!stack.isEmpty()) {

            TreeNode<Integer> node = stack.pop();


            // =================================================================
            // NULL
            // =================================================================

            if (node == null) {

                result.add("null");

                continue;
            }


            // =================================================================
            // PROCESS ROOT
            // =================================================================

            result.add(String.valueOf(node.data));


            // =================================================================
            // PUSH RIGHT FIRST
            // =================================================================
            //
            // Stack:
            //
            //      RIGHT
            //
            stack.push(node.right);


            // =================================================================
            // PUSH LEFT SECOND
            // =================================================================
            //
            // Stack:
            //
            //      RIGHT
            //      LEFT    <- TOP
            //
            // Therefore LEFT will be processed first.
            //
            stack.push(node.left);
        }


        return result;
    }


    // =========================================================================
    // ITERATIVE DFS TRACE
    // =========================================================================

    /*
     *
     * Tree:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * Start:
     *
     * stack:
     *
     *      [1]
     *
     *
     * Pop 1:
     *
     * result:
     *
     *      [1]
     *
     * Push right (3)
     * Push left  (2)
     *
     * stack:
     *
     *      [3, 2]
     *
     *              ^
     *             TOP
     *
     *
     * Pop 2:
     *
     * result:
     *
     *      [1, 2]
     *
     * Push:
     *
     *      null
     *      null
     *
     *
     * Then:
     *
     *      [1, 2, null, null]
     *
     *
     * Next:
     *
     * Pop 3:
     *
     * result:
     *
     *      [1, 2, null, null, 3]
     *
     *
     * Push 3.right = null
     * Push 3.left = 4
     *
     *
     * Then process 4:
     *
     *      [1, 2, null, null, 3, 4, null, null, null]
     *
     *
     * Exactly the same preorder representation.
     *
     */


    // =========================================================================
    // 6. SERIALIZE INTO A SINGLE STRING
    // =========================================================================

    /**
     * Instead of returning:
     *
     *      List<String>
     *
     * we can create:
     *
     *      String
     *
     *
     * Example:
     *
     *      "1,2,null,null,3,4,null,null,null,"
     *
     *
     * StringBuilder is useful because repeatedly doing:
     *
     *      string = string + value
     *
     * can create many intermediate String objects.
     *
     *
     * StringBuilder lets us efficiently append values.
     */
    public static String serializeToString(
            TreeNode<Integer> root) {

        StringBuilder sb = new StringBuilder();


        /*
         * Build preorder serialization.
         */
        serializeStringHelper(root, sb);


        return sb.toString();
    }


    /**
     * Recursive helper for String serialization.
     */
    private static void serializeStringHelper(
            TreeNode<Integer> node,
            StringBuilder sb) {

        // =====================================================================
        // NULL
        // =====================================================================

        if (node == null) {

            sb.append("null,");

            return;
        }


        // =====================================================================
        // CURRENT NODE
        // =====================================================================

        sb.append(node.data).append(",");


        // =====================================================================
        // LEFT
        // =====================================================================

        serializeStringHelper(node.left, sb);


        // =====================================================================
        // RIGHT
        // =====================================================================

        serializeStringHelper(node.right, sb);
    }


    // =========================================================================
    // STRING SERIALIZATION EXAMPLE
    // =========================================================================

    /*
     *
     * Tree:
     *
     *                 1
     *                / \
     *               2   3
     *                  /
     *                 4
     *
     *
     * Result:
     *
     *      "1,2,null,null,3,4,null,null,null,"
     *
     *
     * Think of it as:
     *
     *      1
     *      |
     *      2
     *      |
     *      null
     *      |
     *      null
     *      |
     *      3
     *      |
     *      4
     *      |
     *      null
     *      |
     *      null
     *      |
     *      null
     *
     *
     * The comma is simply our delimiter.
     *
     * It tells us where one value ends and the next begins.
     */


    // =========================================================================
    // 7. DESERIALIZE SINGLE STRING
    // =========================================================================

    /**
     * Convert:
     *
     *      "1,2,null,null,3,4,null,null,null,"
     *
     * back into a binary tree.
     */
    public static TreeNode<Integer> deserializeFromString(
            String data) {

        /*
         * Split the string into individual tokens.
         *
         * Example:
         *
         *      "1,2,null,null,3"
         *
         * becomes:
         *
         *      ["1", "2", "null", "null", "3"]
         */
        String[] arr = data.split(",");


        /*
         * Same pointer idea as before.
         *
         * index[0] tells us:
         *
         *      "Which token should I consume next?"
         */
        int[] index = new int[1];


        return deserializeStringHelper(arr, index);
    }


    /**
     * Recursive string deserialization.
     *
     * This is almost identical to List<String> deserialization.
     *
     * Only the input container changed:
     *
     *      List<String>
     *
     * became:
     *
     *      String[]
     */
    private static TreeNode<Integer> deserializeStringHelper(
            String[] arr,
            int[] index) {

        // =====================================================================
        // READ CURRENT VALUE
        // =====================================================================

        String val = arr[index[0]];


        // Consume it.
        index[0]++;


        // =====================================================================
        // NULL
        // =====================================================================

        if (val.equals("null")) {
            return null;
        }


        // =====================================================================
        // CREATE NODE
        // =====================================================================

        TreeNode<Integer> node =
                new TreeNode<>(Integer.parseInt(val));


        // =====================================================================
        // BUILD LEFT
        // =====================================================================

        node.left =
                deserializeStringHelper(arr, index);


        // =====================================================================
        // BUILD RIGHT
        // =====================================================================

        node.right =
                deserializeStringHelper(arr, index);


        return node;
    }


    // =========================================================================
    // 8. THE MOST IMPORTANT RECURSION IDEA
    // =========================================================================

    /*
     *
     * If you understand THIS, you understand the whole problem.
     *
     *
     * Serialization:
     *
     *      serialize(node)
     *
     * means:
     *
     *      "Serialize the entire subtree rooted at node."
     *
     *
     * Deserialization:
     *
     *      deserialize()
     *
     * means:
     *
     *      "Read enough values from the stream to build ONE COMPLETE
     *       subtree and return its root."
     *
     *
     * This is why the recursion works.
     *
     *
     * -------------------------------------------------------------------------
     * DESERIALIZATION CONTRACT
     * -------------------------------------------------------------------------
     *
     * Every call:
     *
     *      deserialize(...)
     *
     * consumes exactly one subtree from the stream.
     *
     *
     * If the value is:
     *
     *      null
     *
     * then that subtree is empty.
     *
     *
     * Otherwise:
     *
     *      value
     *       |
     *       +---- deserialize LEFT
     *       |
     *       +---- deserialize RIGHT
     *
     *
     * This is exactly the definition of a binary tree.
     *
     */


    // =========================================================================
    // 9. WHY NULL IS SO POWERFUL
    // =========================================================================

    /*
     *
     * Consider:
     *
     *      [1, 2]
     *
     * Impossible to know:
     *
     *
     *      1             1
     *     /               \
     *    2                 2
     *
     *
     * But:
     *
     *
     *      [1, 2, null, null, null]
     *
     * means:
     *
     *      1
     *     /
     *    2
     *
     *
     * While:
     *
     *      [1, null, 2, null, null]
     *
     * means:
     *
     *      1
     *       \
     *        2
     *
     *
     * Therefore:
     *
     *      NULL = structural information.
     *
     *
     * It is NOT useless data.
     *
     */


    // =========================================================================
    // 10. EMPTY TREE
    // =========================================================================

    /*
     *
     * What happens if:
     *
     *      root == null
     *
     *
     * Recursive DFS serialization:
     *
     *      serializeHelper(null)
     *
     * stores:
     *
     *      [null]
     *
     *
     * Therefore:
     *
     *      serialize(empty tree)
     *          =
     *      [null]
     *
     *
     * Deserialization sees:
     *
     *      null
     *
     * and returns:
     *
     *      null
     *
     *
     * So:
     *
     *      empty tree
     *
     * correctly round-trips.
     *
     */


    // =========================================================================
    // 11. COMPLEXITY
    // =========================================================================

    /*
     *
     * Let:
     *
     *      n = number of actual nodes.
     *
     *
     * -------------------------------------------------------------------------
     * SERIALIZATION
     * -------------------------------------------------------------------------
     *
     * Every node is visited once.
     *
     * Every null child is also recorded.
     *
     *
     * A binary tree with n nodes has n + 1 null child pointers.
     *
     * Therefore total serialized entries are roughly:
     *
     *      2n + 1
     *
     *
     * So:
     *
     *      TIME  = O(n)
     *      SPACE = O(n)
     *
     *
     * -------------------------------------------------------------------------
     * DESERIALIZATION
     * -------------------------------------------------------------------------
     *
     * Every serialized value is consumed once.
     *
     * Therefore:
     *
     *      TIME = O(n)
     *
     *
     * Recursive call stack:
     *
     *      O(h)
     *
     * where h = height of tree.
     *
     *
     * Worst case:
     *
     *      h = n
     *
     *
     * Therefore recursion stack can be:
     *
     *      O(n)
     *
     *
     * Balanced tree:
     *
     *      h = O(log n)
     *
     *
     * So recursion stack:
     *
     *      O(h)
     *
     *
     * Important:
     *
     * Output itself also requires O(n) space.
     *
     */


    // =========================================================================
    // 12. DFS VS BFS
    // =========================================================================

    /*
     *
     *                         DFS             BFS
     *                         ---             ---
     *
     * Traversal:              Preorder        Level order
     *
     * Structure:              Recursive       Queue
     *
     * Deserialization:        Very natural    Slightly more bookkeeping
     *
     * Code:                   Shorter         Longer
     *
     * Recursion:              Yes             No
     *
     *
     * Example:
     *
     * DFS:
     *
     *      1,2,null,null,3,4,null,null,null
     *
     *
     * BFS:
     *
     *      1,2,3,null,null,4,null,null,null
     *
     *
     * BOTH are valid.
     *
     * The important thing is:
     *
     *      SERIALIZATION AND DESERIALIZATION
     *
     * must use the SAME format.
     */


    // =========================================================================
    // 13. INTERVIEW QUESTIONS
    // =========================================================================

    /*
     *
     * -------------------------------------------------------------------------
     * Q1. Why can't we serialize only node values?
     * -------------------------------------------------------------------------
     *
     * Because structure is lost.
     *
     * Example:
     *
     *      1        1
     *     /          \
     *    2            2
     *
     * Both can produce:
     *
     *      [1,2]
     *
     *
     * -------------------------------------------------------------------------
     * Q2. Why store null?
     * -------------------------------------------------------------------------
     *
     * To preserve the exact structure of the tree.
     *
     *
     * -------------------------------------------------------------------------
     * Q3. Why preorder?
     * -------------------------------------------------------------------------
     *
     * Preorder processes:
     *
     *      ROOT -> LEFT -> RIGHT
     *
     * Therefore when deserializing:
     *
     *      first value gives root,
     *      next values construct left,
     *      remaining values construct right.
     *
     *
     * -------------------------------------------------------------------------
     * Q4. Can we use inorder?
     * -------------------------------------------------------------------------
     *
     * Inorder alone is NOT enough.
     *
     * Even with null markers, some serialization strategies need
     * additional care depending on the exact format.
     *
     * Preorder is preferred because root comes first and reconstruction
     * becomes naturally recursive.
     *
     *
     * -------------------------------------------------------------------------
     * Q5. Can we use postorder?
     * -------------------------------------------------------------------------
     *
     * Yes.
     *
     * Postorder:
     *
     *      LEFT -> RIGHT -> ROOT
     *
     * is also capable of representing the tree with null markers.
     *
     * Preorder is simply more convenient to explain and implement.
     *
     *
     * -------------------------------------------------------------------------
     * Q6. Can we use BFS?
     * -------------------------------------------------------------------------
     *
     * Absolutely.
     *
     * Queue-based level order works perfectly as long as null information
     * is preserved.
     *
     *
     * -------------------------------------------------------------------------
     * Q7. Why int[] instead of int?
     * -------------------------------------------------------------------------
     *
     * Java passes primitive values by value.
     *
     * If we did:
     *
     *      deserializeHelper(stream, index)
     *
     * where index is int:
     *
     * each recursive call would get its own copy.
     *
     *
     * Using:
     *
     *      int[]
     *
     * gives all recursive calls access to the same mutable object.
     *
     *
     * -------------------------------------------------------------------------
     * Q8. Could we use a global index?
     * -------------------------------------------------------------------------
     *
     * Yes, but it is generally less clean.
     *
     * Example:
     *
     *      private static int index;
     *
     * Then recursive calls modify it.
     *
     * But global mutable state can cause problems if the class is reused
     * concurrently or if multiple deserializations happen.
     *
     * Passing the index explicitly is cleaner.
     *
     *
     * -------------------------------------------------------------------------
     * Q9. Why StringBuilder?
     * -------------------------------------------------------------------------
     *
     * Because repeatedly concatenating Strings can create many temporary
     * String objects.
     *
     * StringBuilder allows efficient append operations.
     *
     *
     * -------------------------------------------------------------------------
     * Q10. Why push RIGHT before LEFT in iterative DFS?
     * -------------------------------------------------------------------------
     *
     * Because Stack is LIFO.
     *
     * We want:
     *
     *      LEFT first
     *
     * Therefore:
     *
     *      push RIGHT
     *      push LEFT
     *
     * gives:
     *
     *      LEFT at the top.
     *
     */


    // =========================================================================
    // 14. THE WHOLE PROBLEM IN ONE PICTURE
    // =========================================================================

    /*
     *
     *
     *                         TREE
     *                           |
     *                           |
     *                    SERIALIZATION
     *                           |
     *               +-----------+-----------+
     *               |                       |
     *              DFS                     BFS
     *               |                       |
     *          preorder                 level order
     *               |                       |
     *               +-----------+-----------+
     *                           |
     *                       NULL MARKERS
     *                           |
     *                           v
     *                    SERIALIZED DATA
     *                           |
     *                           |
     *                    DESERIALIZATION
     *                           |
     *               +-----------+-----------+
     *               |                       |
     *              DFS                     BFS
     *               |                       |
     *          recursion                  queue
     *               |                       |
     *               +-----------+-----------+
     *                           |
     *                           v
     *                         TREE
     *
     *
     */


    // =========================================================================
    // 15. QUICK MEMORY TRICK
    // =========================================================================

    /*
     *
     * If you forget the implementation in an interview, remember:
     *
     *
     * SERIALIZE:
     *
     *      if null:
     *          write NULL
     *
     *      write node
     *      serialize left
     *      serialize right
     *
     *
     * DESERIALIZE:
     *
     *      read value
     *
     *      if NULL:
     *          return null
     *
     *      create node
     *      node.left  = deserialize()
     *      node.right = deserialize()
     *
     *
     * That's basically the entire problem.
     *
     */


    // =========================================================================
    // 16. FINAL INTERVIEW SUMMARY
    // =========================================================================

    /*
     *
     *                         SERIALIZE
     *                             |
     *                             v
     *                    Tree -> Data
     *
     *
     *                         DESERIALIZE
     *                             |
     *                             v
     *                    Data -> Tree
     *
     *
     * KEY IDEA:
     *
     *      Values alone are NOT enough.
     *
     *      Values + NULL markers = exact structure.
     *
     *
     * Most standard solution:
     *
     *      PREORDER DFS + NULL markers
     *
     *
     * Preorder:
     *
     *      ROOT -> LEFT -> RIGHT
     *
     *
     * Serialization:
     *
     *      if null -> "null"
     *      else:
     *          value
     *          serialize(left)
     *          serialize(right)
     *
     *
     * Deserialization:
     *
     *      read value
     *
     *      if null -> null
     *
     *      create node
     *
     *      left  = deserialize()
     *
     *      right = deserialize()
     *
     *
     * Complexity:
     *
     *      Time:
     *          O(n)
     *
     *      Space:
     *          O(n)
     *
     *      Recursion stack:
     *          O(h)
     *
     *
     * The most important thing to understand is NOT the syntax.
     *
     * It is this:
     *
     *
     *      "Every recursive deserialize() call consumes exactly one
     *       complete subtree from the serialized stream."
     *
     *
     * Once that clicks, the whole problem becomes much easier.
     *
     */
}
